atom_H_offset_x: 0.35
atom_H_offset_y: -0.5
atom_alignment: best
atom_charge_offset: 0.25
atom_color_scheme:
  C: black
  N: green
  O: red
  S: yellow
atom_font_bold: false
atom_font_color: black
atom_font_family: Arial
atom_font_size: 1
atom_global_offset_x: 0.03
atom_global_offset_y: -0.07
atom_numbers_box_type: bottom_center
atom_numbers_box_x: 0.4
atom_numbers_box_y: 0.4
atom_numbers_font_bold: false
atom_numbers_font_color: tan
atom_numbers_font_family: Arial
atom_numbers_font_size: 0.5
atom_numbers_offset: 0.3
atom_numbers_show: false
atom_show_carbons: false
atom_text_x_offset: 0.1
atom_text_y_offset: 0.07
auto_center: true
auto_rotate: true
bond_alignment: best
bond_color: black
bond_double_center_length: 0.7
bond_double_center_length_double: 0.3
bond_double_offset: 0.25
bond_double_offset_length: 0.7
bond_length: 1
bond_numbers_box_type: bottom_center
bond_numbers_box_x: 0.3
bond_numbers_box_y: 0.3
bond_numbers_font_bold: false
bond_numbers_font_color: gray
bond_numbers_font_family: Arial
bond_numbers_font_size: 0.5
bond_numbers_offset: 0.2
bond_numbers_show: false
bond_offset: 0.6
bond_stereo_offset: 0.23
bond_stereo_wedge_number_lines: 6
bond_triple_length: 1
bond_triple_offset: 0.18
bond_width: 2
debug: false
debug_atom_vector_color: red
debug_atom_vector_dash: null
debug_atom_vector_head_height: 0.1
debug_atom_vector_head_width: 0.1
debug_atom_vector_length: 0.3
debug_atom_vector_line_width: 2
debug_atom_vector_style: 0
debug_bond_vector_color: green
debug_bond_vector_dash: null
debug_bond_vector_head_height: 0.1
debug_bond_vector_head_width: 0.1
debug_bond_vector_length: 0.3
debug_bond_vector_line_width: 2
debug_bond_vector_perp_color: blue
debug_bond_vector_style: 0
debug_molecule_color: gray
debug_molecule_dash: dash
debug_molecule_line_width: 3
debug_molecule_size: 15
debug_show_atom_vector: true
debug_show_bond_perpendicular: true
debug_show_bond_vector: true
debug_show_molecule: true
draw_order:
- bonds
- atoms
- debug
- bond_numbers
- atom_numbers
- label
label_auto_wrap: true
label_auto_wrap_length: 25
label_font_bold: false
label_font_color: black
label_font_family: Arial
label_font_size: 1
label_location: bottom
label_pad: 1
label_show: true
matplotlib_dpi: 100
plot_background_color: white
plot_buffer: 0.01
plot_height: 560
plot_width: 700
plotter: matplotlib
sub_plotter: null